:: Set variables for the current window.
set LEMURS_POSTRGRES_HOST=localhost:5432
set LEMURS_POSTRGRES_USERNAME=
set LEMURS_POSTRGRES_PASSWORD=

:: Set actual environment variable.
setx LEMURS_POSTRGRES_HOST          %LEMURS_POSTRGRES_HOST% /m
setx LEMURS_POSTRGRES_USERNAME      %LEMURS_POSTRGRES_USERNAME% /m
setx LEMURS_POSTRGRES_PASSWORD      %LEMURS_POSTRGRES_PASSWORD% /m