services:
  db: &db
    profiles:
      - base
    container_name: lemurs-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${LEMURS_POSTRGRES_USERNAME}
      POSTGRES_PASSWORD: ${LEMURS_POSTRGRES_PASSWORD}
      POSTGRES_DB: lemurs
    volumes:
      - lemurs-data:/var/lib/postgresql/data 
      - ./database/createTables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - lemurs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
  db-dev: 
    profiles:
      - dev
      - dev-partial
    <<: *db
    ports:
      - 5432:5432
  db-prod:
    profiles:
      - prod
    <<: *db
    ports:
      - 5432:5432
  api: &api
    profiles:
      - base
    container_name: lemurs-api
    image: lemurs-api-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${LEMURS_API_PORT}:8080
    restart: always
    environment:
      LEMURS_POSTRGRES_HOST: lemurs-db:5432
      LEMURS_POSTRGRES_USERNAME: ${LEMURS_POSTRGRES_USERNAME}
      LEMURS_POSTRGRES_PASSWORD: ${LEMURS_POSTRGRES_PASSWORD}
      LEMURS_SIGNATURE: ${LEMURS_SIGNATURE}
      LEMURS_API_PORT: 8080
      LEMURS_MICROSOFT_TENANT_ID: ${LEMURS_MICROSOFT_TENANT_ID}
      LEMURS_MICROSOFT_APP_ID: ${LEMURS_MICROSOFT_APP_ID}
      LEMURS_MICROSOFT_SECRET: ${LEMURS_MICROSOFT_SECRET}
    networks:
      - lemurs-network
  api-dev: 
    profiles:
      - dev
    <<: *api
    depends_on:
      - db-dev
  api-prod:
    profiles:
      - prod
    <<: *api
    depends_on:
      - db-prod
volumes:
  lemurs-data:
    driver: local
networks:
  lemurs-network:
    driver: bridge