services:
  # === Database Config ===
  db: &db
    profiles:
      - base
    container_name: lemurs-db
    image: lemurs-db-image
    restart: always
    build:
      context: ./database/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${LEMURS_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${LEMURS_POSTGRES_PASSWORD}
      POSTGRES_DB: lemurs
    volumes:
      - lemurs-data:/var/lib/postgresql/data 
    networks:
      - lemurs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  # Database Dev Config
  db-dev: 
    profiles:
      - dev
      - dev-partial
    <<: *db
    ports:
      - 5432:5432

  # Database Prod Config
  db-prod:
    profiles:
      - prod
    <<: *db

  # === API Config ===
  api: &api
    profiles:
      - base
    container_name: lemurs-api
    image: lemurs-api-image
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    environment:
      LEMURS_POSTGRES_HOST: lemurs-db:5432
      LEMURS_POSTGRES_USERNAME: ${LEMURS_POSTGRES_USERNAME}
      LEMURS_POSTGRES_PASSWORD: ${LEMURS_POSTGRES_PASSWORD}
      LEMURS_SIGNATURE: ${LEMURS_SIGNATURE}
      LEMURS_MICROSOFT_TENANT_ID: ${LEMURS_MICROSOFT_TENANT_ID}
      LEMURS_MICROSOFT_APP_ID: ${LEMURS_MICROSOFT_APP_ID}
      LEMURS_MICROSOFT_SECRET: ${LEMURS_MICROSOFT_SECRET}
      LEMURS_EMAIL_ADDRESS: ${LEMURS_EMAIL_ADDRESS}
      LEMURS_EMAIL_HOST: ${LEMURS_EMAIL_HOST}
      LEMURS_EMAIL_PORT: ${LEMURS_EMAIL_PORT}
      LEMURS_EMAIL_USERNAME: ${LEMURS_EMAIL_USERNAME}
      LEMURS_EMAIL_PASSWORD: ${LEMURS_EMAIL_PASSWORD}
    networks:
      - lemurs-network

  # API Dev Config
  api-dev: 
    profiles:
      - dev
    <<: *api
    depends_on:
      - db-dev

  # API Prod Config
  api-prod:
    profiles:
      - prod
    <<: *api
    depends_on:
      - db-prod

  # === Web Config ===
  web: &web
    profiles:
      - base
    container_name: lemurs-web
    image: lemurs-web-image
    restart: always
    build:
      context: ./web/
      dockerfile: Dockerfile
      args:
        REACT_APP_LEMURS_API_HOST: ${REACT_APP_LEMURS_API_HOST}
    networks:
      - lemurs-network

  # Web Dev Config
  web-dev: 
    profiles:
      - dev
      - dev-partial
    <<: *web
    ports:
      - 3000:80
    depends_on:
      - db-dev
      - api-dev

  # Web Prod Config
  web-prod:
    profiles:
      - prod
    <<: *web
    depends_on:
      - db-prod
      - api-prod

  # === Proxy Config ===
  proxy: &proxy
    profiles:
      - base
    container_name: lemurs-proxy
    image: lemurs-proxy-image
    restart: always
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    networks:
      - lemurs-network
    ports:
      - 80:80

  # Proxy Dev Config
  proxy-dev:
    profiles:
      - dev
      - dev-partial
    <<: *proxy
    depends_on:
      - db-dev
      - api-dev
      - web-dev
  
  # Proxy Prod Config
  proxy-prod:
    profiles:
      - prod
    <<: *proxy
    depends_on:
      - db-prod
      - api-prod
      - web-prod

# Volumes
volumes:
  lemurs-data:
    driver: local

# Networks
networks:
  lemurs-network:
    driver: bridge