spring.application.name=lemurs-api

spring.datasource.url=jdbc:postgresql://${LEMURS_DB_HOST}/lemurs
spring.datasource.username=${LEMURS_POSTRGRES_USERNAME}
spring.datasource.password=${LEMURS_POSTRGRES_PASSWORD}