spring.application.name=lemurs-api

server.port=${LEMURS_API_PORT}

spring.datasource.url=jdbc:postgresql://${LEMURS_POSTRGRES_HOST}/lemurs
spring.datasource.username=${LEMURS_POSTRGRES_USERNAME}
spring.datasource.password=${LEMURS_POSTRGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

spring.mail.host=${LEMURS_EMAIL_HOST}
spring.mail.port=${LEMURS_EMAIL_PORT}
spring.mail.username=${LEMURS_EMAIL_USERNAME}
spring.mail.password=${LEMURS_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
