# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the current directory to the container
COPY . .

# Make port 5433 available to the world outside this container
EXPOSE 5433

# Run dashboard.py when the container launches
CMD ["python", "dashboard.py"]
