spring.application.name=lemurs-api

server.port=8080

spring.datasource.url=jdbc:postgresql://${LEMURS_POSTGRES_HOST}/lemurs
spring.datasource.username=${LEMURS_POSTGRES_USERNAME}
spring.datasource.password=${LEMURS_POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

spring.mail.host=${LEMURS_EMAIL_HOST}
spring.mail.port=${LEMURS_EMAIL_PORT}
spring.mail.username=${LEMURS_EMAIL_USERNAME}
spring.mail.password=${LEMURS_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Determines if the auth cookie should use the 'Secure' flag.
# Set to 'true' in production (HTTPS)
# Set to 'false' in local development (HTTP)
app.security.cookie-secure=true