CREATE TABLE app_user (
	id INT GENERATED ALWAYS AS IDENTITY,
	umass_id INT NOT NULL,
	is_disabled BOOLEAN NOT NULL,
	is_deleted BOOLEAN NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (umass_id)
);

CREATE TABLE data (
	id INT GENERATED ALWAYS AS IDENTITY,
	type VARCHAR(255) NOT NULL,
  data JSONB NOT NULL,
  status INT NOT NULL,
	PRIMARY KEY (id)
);