CREATE TABLE data (
	id INT GENERATED ALWAYS AS IDENTITY,
	type VARCHAR(255) NOT NULL,
  data JSONB NOT NULL,
  status INT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE survey (
	id INT GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  total INT NOT NULL, 
  PRIMARY KEY (id)
);
