--- Data for surveys.
INSERT INTO "survey" ("id", "name") OVERRIDING SYSTEM VALUE VALUES
	('0', '2024-2025 Daily Morning Questions'),
	('1', '2024-2025 Daily Afternoon Questions'),
	('2', 'PQP 9');

--- Data for question.
INSERT INTO "question" ("id", "question", "style", "options", "parent_question_id", "prerequisite_question_id", "prerequisite_answer", "requirements") OVERRIDING SYSTEM VALUE VALUES
	(0, 'Daily Suicidal and Risky Items', 'category', NULL, NULL, NULL, NULL, NULL),
    (1, 'Since your last prompt:  ', 'parent-question', NULL, NULL, NULL, NULL, NULL),
    (2, 'I wanted to die', '5-scale-much', NULL, '1', NULL, NULL, NULL),
    (3, 'I thought about taking my life', '5-scale-much', NULL, '1', NULL, NULL, NULL),
    (4, 'Since the last prompt, have you… ', 'parent-question', NULL, NULL, NULL, NULL, NULL),
    (5, 'Considered a specific suicide method or made preparations for your death ', '5-scale-much', NULL, '4', NULL, NULL, NULL),
    (6, 'At this moment: ', 'parent-question', NULL, NULL, NULL, NULL, NULL),
    (7, 'How intense was your desire to kill yourself? ', '5-scale-intense', NULL, '6', NULL, NULL, NULL),
    (8, 'Do you intend to kill yourself right now?', 'yes-no', NULL, '6', '7', '2,3,4,5', NULL),
    (9, 'How strong was your urge to injure yourself without any intent to die? ', '5-scale-intense', NULL, '6', NULL, NULL, NULL),
    (10, 'Since the last prompt, have you', 'parent-question', NULL, NULL, NULL, NULL, NULL),
    (11, 'Injured yourself without any intent to die ', 'yes-no', NULL, '10', NULL, NULL, NULL),
    (12, 'Have you attempted suicide?', 'yes-no', NULL, '10', NULL, NULL, NULL),
    (13, 'Were you severely injured or did you require medical intervention? ', 'yes-no', NULL, '10', '12', 'yes', NULL),
    (14, 'Since the last prompt, have you...', 'parent-question', NULL, NULL, NULL, NULL, NULL),
    (15, 'Eaten an unusually large amount of food and experienced a sense of loss of control at the time and were not under the influence ', 'yes-no', NULL, '14', NULL, NULL, NULL),
    (16, 'Have you made yourself sick (vomit) or taken laxatives as a means of controlling your weight or shape ', 'yes-no', NULL, '14', NULL, NULL, NULL),
    (17, 'Gotten drunk', 'yes-no', NULL, '14', NULL, NULL, NULL),
    (18, 'Took drugs or medication not as prescribed', 'yes-no', NULL, '14', NULL, NULL, NULL),
    (19, 'Daily Emotion Items', 'category', NULL, NULL, NULL, NULL, NULL),
    (20, 'Please rate each item on a 5-point scale (1 = Not at all; 5 = Very much).

Since the last prompt, I felt:', 'parent-question', NULL, NULL, NULL, NULL, NULL),
    (21, 'Content', '5-scale-much', NULL, '20', NULL, NULL, NULL),
    (22, 'Cheerful', '5-scale-much', NULL, '20', NULL, NULL, NULL),
    (23, 'Nervous', '5-scale-much', NULL, '20', NULL, NULL, NULL),
    (24, 'Sad', '5-scale-much', NULL, '20', NULL, NULL, NULL),
    (25, 'Useless', '5-scale-much', NULL, '20', NULL, NULL, NULL),
    (26, 'Lonely', '5-scale-much', NULL, '20', NULL, NULL, NULL),
    (27, 'Like I might as well give up because there is nothing I can do about making things better for myself', '5-scale-much', NULL, '20', NULL, NULL, NULL),
    (28, 'Like people usually do not understand my experiences', '5-scale-much', NULL, '20', NULL, NULL, NULL),
    (29, 'Daily Context', 'category', NULL, NULL, NULL, NULL, NULL),
    (30, 'Please rate each item on a 5-point scale (1 = Not at all; 5 = All the time).

Since the last prompt, I have:', 'parent-question', NULL, NULL, NULL, NULL, NULL),
    (31, 'Gotten into an argument or disagreement with a friend, significant other or family member', '5-scale-time', NULL, '30', NULL, NULL, NULL),
    (32, 'Felt insulted or criticized', '5-scale-time', NULL, '30', NULL, NULL, NULL),
    (33, 'Felt rejected, abandoned, excluded or left out', '5-scale-time', NULL, '30', NULL, NULL, NULL),
    (34, 'Felt admired or complimented', '5-scale-time', NULL, '30', NULL, NULL, NULL),
    (35, 'Felt you were wanted or included', '5-scale-time', NULL, '30', NULL, NULL, NULL),
    (36, 'Failed or performed poorly at something', '5-scale-time', NULL, '30', NULL, NULL, NULL),
    (37, 'Performed well or succeeded at something', '5-scale-time', NULL, '30', NULL, NULL, NULL),
    (38, 'Minority Stress Contexts', 'category', NULL, NULL, NULL, NULL, ARRAY['LGBT']),
    (39, 'Today, I have:', 'parent-question', NULL, NULL, NULL, NULL, ARRAY['LGBT']),
    (40, 'Avoided the subjects of sex, love, attraction, or relationships to conceal my sexual orientation  ', '5-scale-time', NULL, 39, NULL, NULL, ARRAY['LGBT']),
    (41, 'Felt alienated from myself because of my LGBT identity', '5-scale-time', NULL, 39, NULL, NULL, ARRAY['LGBT']),
    (42, 'Worried that people will reject me or treat me unfavorably because I''m LGBT', '5-scale-time', NULL, 39, NULL, NULL, ARRAY['LGBT']),
    (43, 'Been treated unfairly by others because I am LGBT', '5-scale-time', NULL, 39, NULL, NULL, ARRAY['LGBT']),
    (44, 'Been exposed to anti-LGBT media/social media content (e.g., online hate speech, news of policy that would reduce LGBT civil rights, etc.)', '5-scale-time', NULL, 39, NULL, NULL, ARRAY['LGBT']),
    (45, 'Daily Emotion Regulation', 'category', NULL, NULL, NULL, NULL, NULL),
    (46, 'Please rate the following based on how you felt since you last prompt when you felt negative emotions: ', 'parent-question', NULL, NULL, NULL, NULL, NULL),
    (47, 'When I felt negative emotions, I had difficulty focusing on other things', '4-scale-true', NULL, '46', NULL, NULL, NULL),
    (48, 'When I felt negative emotions, I thought I should not feel that way', '4-scale-true', NULL, '46', NULL, NULL, NULL),
    (49, 'When I felt negative emotions, I had difficulty controlling my behaviors', '4-scale-true', NULL, '46', NULL, NULL, NULL),
    (50, 'When I felt negative emotions, I didn’t pay attention to how I felt', '4-scale-true', NULL, '46', NULL, NULL, NULL),
    (51, 'When I felt negative emotions, I thought they would last for a long time', '4-scale-true', NULL, '46', NULL, NULL, NULL),
    (52, 'When I felt negative emotions, I had difficulty making sense out of them', '4-scale-true', NULL, '46', NULL, NULL, NULL),
    (53, 'Daily Sleep', 'category', NULL, NULL, NULL, NULL, NULL),
    (54, 'What time did you fall asleep last night? (HH:MM am/pm)', 'time-picker', NULL, '55', NULL, NULL, NULL),
    (55, 'What time did you wake up this morning? (HH:MM am/pm)', 'time-picker', NULL, '55', NULL, NULL, NULL),
    (56, 'How would you rate the quality of your sleep? ', '5-scale-sleep', NULL, '55', NULL, NULL, NULL),
    (57, 'PHQ-9', 'category', NULL, NULL, NULL, NULL, NULL),
    (58, 'Over the last 2 weeks, how often have you been bothered by any of the following problems?  ', 'parent-question', NULL, NULL, NULL, NULL, NULL),
    (59, 'Little interest or pleasure in doing things', '4-scale-zero', NULL, '58', NULL, NULL, NULL),
    (60, 'Feeling down, depressed or hopeless', '4-scale-zero', NULL, '58', NULL, NULL, NULL),
    (61, 'Trouble falling or staying asleep or sleeping too much', '4-scale-zero', NULL, '58', NULL, NULL, NULL),
    (62, 'Feeling tired or having little energy', '4-scale-zero', NULL, '58', NULL, NULL, NULL),
    (63, 'Poor appetite or overeating', '4-scale-zero', NULL, '58', NULL, NULL, NULL),
    (64, 'Feeling bad about yourself - or that you are a failure or have let yourself or your family down', '4-scale-zero', NULL, '58', NULL, NULL, NULL),
    (65, 'Trouble concentrating on things such as reading the newspaper or watching television', '4-scale-zero', NULL, '58', NULL, NULL, NULL),
    (66, 'Moving or speaking so slowly that other people could have noticed? Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual', '4-scale-zero', NULL, '58', NULL, NULL, NULL),
    (67, 'Thoughts that you would be better off dead, or thoughts of hurting yourself in some way', '4-scale-zero', NULL, '58', NULL, NULL, NULL),
    (68, ' Do you intend to kill yourself right now?', 'yes-no', NULL, '58', '67', '1,2,3,4', NULL),
    (69, 'If you checked off any problems, how difficult have these problems made it for you to do your work, take care of things at home, or get along with other people? ', '4-scale-difficult', NULL, '58', NULL, NULL, NULL);

--- Data for linking questions with surveys.
INSERT INTO "survey_question" ("survey_id", "question_id", "position") OVERRIDING SYSTEM VALUE VALUES
	('0', '0', '0'),
	('0', '1', '8'),
	('0', '2', '16'),
	('0', '3', '24'),
	('0', '4', '32'),
	('0', '5', '40'),
	('0', '6', '48'),
	('0', '7', '56'),
	('0', '8', '64'),
	('0', '9', '72'),
	('0', '10', '80'),
	('0', '11', '88'),
	('0', '12', '96'),
	('0', '13', '104'),
	('0', '14', '112'),
	('0', '15', '120'),
	('0', '16', '128'),
	('0', '17', '136'),
	('0', '18', '144'),
	('0', '19', '152'),
	('0', '20', '160'),
	('0', '21', '168'),
	('0', '22', '176'),
	('0', '23', '184'),
	('0', '24', '192'),
	('0', '25', '200'),
	('0', '26', '208'),
	('0', '27', '216'),
	('0', '28', '224'),
	('0', '29', '232'),
	('0', '30', '240'),
	('0', '31', '248'),
	('0', '32', '256'),
	('0', '33', '264'),
	('0', '34', '272'),
	('0', '35', '280'),
	('0', '36', '288'),
	('0', '37', '296'),
	('0', '45', '304'),
	('0', '46', '312'),
	('0', '47', '320'),
	('0', '48', '328'),
	('0', '49', '336'),
	('0', '50', '344'),
	('0', '51', '352'),
	('0', '52', '360'),
	('0', '53', '368'),
	('0', '54', '376'),
	('0', '55', '384'),
	('0', '56', '392'),
	('1', '0', '0'),
	('1', '1', '8'),
	('1', '2', '16'),
	('1', '3', '24'),
	('1', '4', '32'),
	('1', '5', '40'),
	('1', '6', '48'),
	('1', '7', '56'),
	('1', '8', '64'),
	('1', '9', '72'),
	('1', '10', '80'),
	('1', '11', '88'),
	('1', '12', '96'),
	('1', '13', '104'),
	('1', '14', '112'),
	('1', '15', '120'),
	('1', '16', '128'),
	('1', '17', '136'),
	('1', '18', '144'),
	('1', '19', '152'),
	('1', '20', '160'),
	('1', '21', '168'),
	('1', '22', '176'),
	('1', '23', '184'),
	('1', '24', '192'),
	('1', '25', '200'),
	('1', '26', '208'),
	('1', '27', '216'),
	('1', '28', '224'),
	('1', '29', '232'),
	('1', '30', '240'),
	('1', '31', '248'),
	('1', '32', '256'),
	('1', '33', '264'),
	('1', '34', '272'),
	('1', '35', '280'),
	('1', '36', '288'),
	('1', '37', '296'),
	('1', '38', '304'),
	('1', '39', '312'),
	('1', '40', '320'),
	('1', '41', '328'),
	('1', '42', '336'),
	('1', '43', '344'),
	('1', '44', '352'),
	('1', '45', '360'),
	('1', '46', '368'),
	('1', '47', '376'),
	('1', '48', '384'),
	('1', '49', '392'),
	('1', '50', '400'),
	('1', '51', '408'),
	('1', '52', '416'),
	('2', '57', '0'),
	('2', '58', '8'),
	('2', '59', '16'),
	('2', '60', '24'),
	('2', '61', '32'),
	('2', '62', '40'),
	('2', '63', '48'),
	('2', '64', '56'),
	('2', '65', '64'),
	('2', '66', '72'),
	('2', '67', '80'),
	('2', '68', '88'),
	('2', '69', '96');

--- Incentive Constants
INSERT INTO "incentive" ("id", "name", "reward") OVERRIDING SYSTEM VALUE VALUES
	('0', 'daily_survey', '3'),
	('1', 'weekly_survey', '5');

-- Goal Constants
INSERT INTO "goal" ("id", "name", "required_daily_surveys", "max_days", "reward") OVERRIDING SYSTEM VALUE VALUES
	('0', '80% Pariticipation Week 1-2', '23', '14', '10'),
	('1', '80% Pariticipation Week 1-3', '34', '21', '15'),
	('2', '80% Total Participation', '45', '28', '25');

-- Survey Availability
INSERT INTO "survey_availability" ("name", "open_time", "close_time") VALUES
	('morning', '08:00:00', '13:00:00'),
	('afternoon', '15:00:00', '20:00:00');