--- Data for surveys.
INSERT INTO "survey" ("id", "name", "is_daily", "is_weekly") OVERRIDING SYSTEM VALUE VALUES
	('0', '2024-2025 Daily Questions', 'TRUE', 'FALSE'),
	('1', 'PQP 9', 'FALSE', 'TRUE');

--- Data for question.
INSERT INTO "question" ("id", "question", "style", "options", "parent_question_id", "prerequisite_question_id", "prerequisite_answer", "requirements") OVERRIDING SYSTEM VALUE VALUES
	('0', 'Daily Suicidal Items', 'category', NULL, NULL, NULL, NULL, NULL),
	('1', 'Since your last response:', 'parent-question', NULL, NULL, NULL, NULL, NULL),
	('2', 'Life is not worth living for me', '5-scale', NULL, '1', NULL, NULL, NULL),
	('3', 'There are more reasons to die than to live for me ', '5-scale', NULL, '1', NULL, NULL, NULL),
	('4', 'I want to die ', '5-scale', NULL, '1', NULL, NULL, NULL),
	('5', 'Since the last survey, have you: ', 'parent-question', NULL, NULL, NULL, NULL, NULL),
	('6', 'Considered a specific suicide method', '5-scale', NULL, '5', NULL, NULL, NULL),
	('7', 'Identified how to acquire your suicide method', '5-scale', NULL, '5', NULL, NULL, NULL),
	('8', 'Made other preparations for your death (e.g. wrote a suicide note, made arrangements) ', '5-scale', NULL, '5', NULL, NULL, NULL),
	('9', 'At this moment:', 'parent-question', NULL, NULL, NULL, NULL, NULL),
	('10', 'How strong was your urge to make a suicide attempt?', '5-scale', NULL, '9', NULL, NULL, NULL),
	('11', 'How intense was your desire to kill yourself', '5-scale', NULL, '9', NULL, NULL, NULL),
	('12', 'How strong was your urge to injure yourself without any intent to die? ', '5-scale', NULL, '9', NULL, NULL, NULL),
	('13', 'Since the last prompt, have you', 'parent-question', NULL, NULL, NULL, NULL, NULL),
	('14', 'Injured yourself without any intent to die ', 'yes-no', NULL, '13', NULL, NULL, NULL),
	('15', 'Have you attempted suicide', 'yes-no', NULL, '13', NULL, NULL, NULL),
	('16', 'Were you severely injured or did you require medical intervention? ', 'yes-no', NULL, '13', '14', 'yes', NULL),
	('17', 'Have you wished you were dead or had thoughts of killing yourself?', 'yes-no', NULL, NULL, NULL, NULL, NULL),
	('18', 'Since you last completed the daily survey:', 'parent-question', NULL, NULL, '16', 'yes', NULL),
	('19', 'How often did you have these thoughts', 'custom-5-scale', '{"Less than once", "Once", "2-3 times", "4-5 times", "More than 5 times"}', '18', '16', 'yes', NULL),
	('20', 'When you had these thoughts how long did they last (at their worst)', 'custom-5-scale', '{"A few seconds or minutes / fleeting", "Less than one hour / some of the time", "One to four hours / a lot of the time", "Four to eight hours / most of the day", "More than 8 hours / persistent or continuous"}', '18', '16', 'yes', NULL),
	('21', 'How intense or powerful were these thoughts ', 'custom-4-scale', '{"Very Weak", "Weak", "Moderate", "Strong"}', '18', '16', 'yes', NULL),
	('22', 'Have you done anything to prepare to kill yourself, such as collecting pills, buying a gun, writing a suicide note, or giving away valuables?', 'yes-no', NULL, '18', '16', 'yes', NULL),
	('23', 'Have you done anything to hurt yourself with at least some intention of killing yourself?', 'yes-no', NULL, '18', '16', 'yes', NULL),
	('24', 'Daily Emotion Items', 'category', NULL, NULL, NULL, NULL, NULL),
	('25', 'I felt:', 'parent-question', NULL, NULL, NULL, NULL, NULL),
	('26', 'Cheerful', '5-scale', NULL, '25', NULL, NULL, NULL),
	('27', 'Happy', '5-scale', NULL, '25', NULL, NULL, NULL),
	('28', 'Afraid', '5-scale', NULL, '25', NULL, NULL, NULL),
	('29', 'Nervous', '5-scale', NULL, '25', NULL, NULL, NULL),
	('30', 'Downhearted', '5-scale', NULL, '25', NULL, NULL, NULL),
	('31', 'Sad', '5-scale', NULL, '25', NULL, NULL, NULL),
	('32', 'Useless', '5-scale', NULL, '25', NULL, NULL, NULL),
	('33', 'Like a burden for others', '5-scale', NULL, '25', NULL, NULL, NULL),
	('34', 'Lonely', '5-scale', NULL, '25', NULL, NULL, NULL),
	('35', 'Like I do not belong', '5-scale', NULL, '25', NULL, NULL, NULL),
	('36', 'My future seems dark for me', '5-scale', NULL, '25', NULL, NULL, NULL),
	('37', 'I might as well give up because there is nothing I can do about making things better for myself', '5-scale', NULL, '25', NULL, NULL, NULL),
	('38', 'Daily Context', 'category', NULL, NULL, NULL, NULL, NULL),
	('39', 'I have:', 'parent-question', NULL, NULL, NULL, NULL, NULL),
	('40', 'Gotten into an argument or disagreement with a friend, significant other or family member', 'yes-no', NULL, '39', NULL, NULL, NULL),
	('41', 'Felt insulted or criticized', 'yes-no', NULL, '39', NULL, NULL, NULL),
	('42', 'Felt rejected, abandoned, excluded or left out', 'yes-no', NULL, '39', NULL, NULL, NULL),
	('43', 'Felt admired or complimented', 'yes-no', NULL, '39', NULL, NULL, NULL),
	('44', 'Felt you were wanted or included', 'yes-no', NULL, '39', NULL, NULL, NULL),
	('45', 'Failed or performed poorly at something', 'yes-no', NULL, '39', NULL, NULL, NULL),
	('46', 'Performed well or succeeded at something', 'yes-no', NULL, '39', NULL, NULL, NULL),
	('47', 'Daily Emotion Regulation', 'category', NULL, NULL, NULL, NULL, NULL),
	('48', 'To what extent did you do the following in order to cope with your emotions', 'parent-question', NULL, NULL, NULL, NULL, NULL),
	('49', 'Come up to with ideas to change', '5-scale', NULL, '48', NULL, NULL, NULL),
	('50', 'Think of the situation', '5-scale', NULL, '48', NULL, NULL, NULL),
	('51', 'Allow or accept your feelings', '5-scale', NULL, '48', NULL, NULL, NULL),
	('52', 'Hide your feelings from', '5-scale', NULL, '48', NULL, NULL, NULL),
	('53', 'Worry or ruminate', '5-scale', NULL, '48', NULL, NULL, NULL),
	('54', 'Avoid thinking about it', '5-scale', NULL, '48', NULL, NULL, NULL),
	('55', 'Daily Sleep', 'category', NULL, NULL, NULL, NULL, NULL),
	('56', 'What time did you fall asleep last night', 'open-response', NULL, '55', NULL, NULL, NULL),
	('57', 'How long did it take you to fall asleep after going to bed', 'open-response', NULL, '55', NULL, NULL, NULL),
	('58', 'Did you experience any nightmares', 'yes-no', NULL, '55', NULL, NULL, NULL),
	('59', 'What time did you wake up this morning', 'open-response', NULL, '55', NULL, NULL, NULL),
	('60', 'How would you rate your quality of sleep', 'custom-5-scale', '{"very bad night of sleep", NULL, NULL, NULL, "very good night of sleep"}', '55', NULL, NULL, NULL),
	('61', 'Daily Other Risk Behaviors', 'category', NULL, NULL, NULL, NULL, NULL),
	('62', 'I hurt myself by cutting, burning, strangling, headbanging, etc', '5-scale', NULL, '61', NULL, NULL, NULL),
	('63', 'I had episodes of binge eating', '5-scale', NULL, '61', NULL, NULL, NULL),
	('64', 'I induced vomiting', '5-scale', NULL, '61', NULL, NULL, NULL),
	('65', 'I displayed high risk behavior by knowingly driving too fast,
running around on the roofs of high buildings, balancing on
bridges, etc.', '5-scale', NULL, '61', NULL, NULL, NULL),
	('66', 'I got drunk', '5-scale', NULL, '61', NULL, NULL, NULL),
	('67', 'I took drugs', '5-scale', NULL, '61', NULL, NULL, NULL),
	('68', 'I took medication that had not been prescribed or if had been prescribed, I took more than the prescribed dose', '5-scale', NULL, '61', NULL, NULL, NULL),
	('69', 'I had outbreaks of uncontrolled anger or physically attacked others', '5-scale', NULL, '61', NULL, NULL, NULL),
	('70', 'I had uncontrollable sexual encounters of which I was later ashamed or which made me angry', '5-scale', NULL, '61', NULL, NULL, NULL),
	('71', 'How often have you been bothered by the following over the past 2 weeks', 'parent-question-custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', NULL, NULL, NULL, NULL),
	('72', 'Little interest or pleasure in doing things', 'custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', '71', NULL, NULL, NULL),
	('73', 'Feeling down, depressed or hopeless', 'custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', '71', NULL, NULL, NULL),
	('74', 'Trouble falling or staying asleep or sleeping too much', 'custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', '71', NULL, NULL, NULL),
	('75', 'Eeeling tired or having little energy', 'custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', '71', NULL, NULL, NULL),
	('76', 'Poor appetite or overeating', 'custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', '71', NULL, NULL, NULL),
	('77', 'Feeling bad about yourself or that you are a failure or have let yourself or your family down', 'custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', '71', NULL, NULL, NULL),
	('78', 'Trouble concentrating on things such as reading the newspaper or watching television', 'custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', '71', NULL, NULL, NULL),
	('79', 'Moving or speaking so slowly that others could have noticed? Or so fidgety or restless that you have been moving a lot more than usual?', 'custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', '71', NULL, NULL, NULL),
	('80', 'Thoughts that you would be better off dead, or thoughts of hurting yourself in some way', 'custom-4-scale', '{"Not at all", "Several Days", "More than half the days", "Nearly every day"}', '71', NULL, NULL, NULL);

--- Data for linking questions with surveys.
INSERT INTO "survey_question" ("survey_id", "question_id", "position") OVERRIDING SYSTEM VALUE VALUES
	('0', '0', '0'),
	('0', '1', '8'),
	('0', '2', '16'),
	('0', '3', '24'),
	('0', '4', '32'),
	('0', '5', '40'),
	('0', '6', '48'),
	('0', '7', '56'),
	('0', '8', '64'),
	('0', '9', '72'),
	('0', '10', '80'),
	('0', '11', '88'),
	('0', '12', '96'),
	('0', '13', '104'),
	('0', '14', '112'),
	('0', '15', '120'),
	('0', '16', '128'),
	('0', '17', '136'),
	('0', '18', '144'),
	('0', '19', '152'),
	('0', '20', '160'),
	('0', '21', '168'),
	('0', '22', '176'),
	('0', '23', '184'),
	('0', '24', '192'),
	('0', '25', '200'),
	('0', '26', '208'),
	('0', '27', '216'),
	('0', '28', '224'),
	('0', '29', '232'),
	('0', '30', '240'),
	('0', '31', '248'),
	('0', '32', '256'),
	('0', '33', '264'),
	('0', '34', '272'),
	('0', '35', '280'),
	('0', '36', '288'),
	('0', '37', '296'),
	('0', '38', '304'),
	('0', '39', '312'),
	('0', '40', '320'),
	('0', '41', '328'),
	('0', '42', '336'),
	('0', '43', '344'),
	('0', '44', '352'),
	('0', '45', '360'),
	('0', '46', '368'),
	('0', '47', '376'),
	('0', '48', '384'),
	('0', '49', '392'),
	('0', '50', '400'),
	('0', '51', '408'),
	('0', '52', '416'),
	('0', '53', '424'),
	('0', '54', '432'),
	('0', '55', '440'),
	('0', '56', '448'),
	('0', '57', '456'),
	('0', '58', '464'),
	('0', '59', '472'),
	('0', '60', '480'),
	('0', '61', '488'),
	('0', '62', '496'),
	('0', '63', '504'),
	('0', '64', '512'),
	('0', '65', '520'),
	('0', '66', '528'),
	('0', '67', '536'),
	('0', '68', '544'),
	('0', '69', '552'),
	('0', '70', '560'),
	('1', '71', '0'),
	('1', '72', '8'),
	('1', '73', '16'),
	('1', '74', '24'),
	('1', '75', '32'),
	('1', '76', '40'),
	('1', '77', '48'),
	('1', '78', '56'),
	('1', '79', '64'),
	('1', '80', '72');