server {
    listen 80;
    
    location /web/ {
        proxy_pass http://lemurs-web:80/;
    }

    location /api/ {
        proxy_pass http://lemurs-api:8080/;
    }
    
    location / {
        return 301 web/;
    }
}