server {
    listen 80;
    client_max_body_size 20M;
    
    location /web/ {
        proxy_pass http://lemurs-web:80/;
    }

    location = /api/validate {
        internal;
        proxy_pass http://lemurs-api:8080/api/validate;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }

    location /api/ {
        proxy_pass http://lemurs-api:8080/;
    }

    location /dashboard/ {
        auth_request /api/validate;
        error_page 401 = /web/;
        proxy_pass http://lemurs-dashboard:5433/;
    }
    
    location / {
        return 301 /web/;
    }
}