import java.util.Properties


plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.3'
	id 'io.spring.dependency-management' version '1.1.6'
	id "com.diffplug.spotless" version "6.25.0"
}
// Load environment variables from .env file

def env = [:]
def envFile = file('.env')
if (envFile.exists()) {
    envFile.eachLine { line ->
        def parts = line.split('=')
        if (parts.length == 2) {
            env[parts[0].trim()] = parts[1].trim()
        }
    }
}

group = 'edu.wpi.lemurs'
version = '0.0.1-SNAPSHOT'

bootJar {
	archiveFileName = 'lemurs-api.jar'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

bootRun {
	environment "LEMURS_EMAIL_HOST", env['LEMURS_EMAIL_HOST']
	environment "LEMURS_EMAIL_PORT", env['LEMURS_EMAIL_PORT']
    environment "LEMURS_POSTGRES_USERNAME", env['LEMURS_POSTGRES_USERNAME']
    environment "LEMURS_POSTGRES_PASSWORD", env['LEMURS_POSTGRES_PASSWORD']
}

dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.34'
	annotationProcessor 'org.projectlombok:lombok:1.18.34'
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web:3.3.2'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc:3.3.2'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.3.2'
	implementation 'org.springframework.boot:spring-boot-starter-security:3.3.2'
	implementation 'org.springframework.boot:spring-boot-starter-mail:3.3.2'
	implementation 'com.google.googlejavaformat:google-java-format:1.23.0'
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	implementation 'org.postgresql:postgresql:42.7.4'
	implementation 'com.google.code.gson:gson:2.11.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.assertj:assertj-core:3.26.3'
	testImplementation 'org.mockito:mockito-core:5.14.2'
}

spotless {
	format 'misc', {
		target '.gitattributes', '.gitignore'
		trimTrailingWhitespace()
		indentWithSpaces(2)
		endWithNewline()
	}

	groovyGradle {
		target '*.gradle'
		greclipse()
	}

	java {
		importOrder()
		removeUnusedImports()

		googleJavaFormat()
		formatAnnotations()
		licenseHeaderFile(file("${project.rootDir}/resources/header.txt"))
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
