server {
    listen 80;
    location / {
      root   /usr/share/nginx/html;
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;
    } 

    location /dashboard/ {
        proxy_pass http://lemurs-dashboard:5433/;
    }
}
